#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require_relative '../lib/repository_merger'
require 'pry'

def main
  Signal.trap('INT') do
    puts 'Aborting...'
    exit(1)
  end

  original_repo_paths = fetch_original_repos_if_needed
  merged_repo_path = create_merged_repo_if_needed

  repo_merger = RepositoryMerger.new(original_repo_paths, merged_repo_path: merged_repo_path)

  repo_merger.commit_message_transformer = proc do |original_commit|
    scope = "[#{original_commit.repo.name.sub(/\Arspec-/, '')}]"
    "#{scope} #{original_commit.message}"
  end

  repo_merger.merge_branches('master')

  # Merged repos without GC tend to have large volume
  Dir.chdir(merged_repo_path) do
    puts 'Running `git gc`...'
    system('git gc')
  end
end

def fetch_original_repos_if_needed
  repo_urls = %w[
    https://github.com/rspec/rspec.git
    https://github.com/rspec/rspec-core.git
    https://github.com/rspec/rspec-expectations.git
    https://github.com/rspec/rspec-mocks.git
    https://github.com/rspec/rspec-support.git
  ]

  original_repos_dir = 'original_repos'

  Dir.mkdir(original_repos_dir) unless Dir.exist?(original_repos_dir)

  repo_paths = Dir.chdir(original_repos_dir) do |current_directory|
    repo_urls.map do |repo_url|
      repo_name = File.basename(repo_url, '.git')

      unless Dir.exist?(repo_name)
        system("git clone #{repo_url}")
      end

      File.join(current_directory, repo_name)
    end
  end

  repo_paths
end

def create_merged_repo_if_needed
  merged_repo_dir = 'merged_repo'

  unless Dir.exist?(merged_repo_dir)
    Dir.mkdir(merged_repo_dir)
    Dir.chdir(merged_repo_dir) do
      system('git init')
    end
  end

  merged_repo_dir
end

main
