require 'digest'
require 'find'

base_directory = "dest/#{`git rev-parse --abbrev-ref HEAD`.chomp}/original_repos"

RSpec.describe 'original RSpec repositories', if: Dir.exist?(base_directory) do
  include FileHelper
  include GitHelper

  around do |example|
    Dir.chdir(base_directory) do
      example.run
    end
  end

  def self.maintenance_branches_in(repo_path)
    Dir.chdir(repo_path) do
      git(['branch', '--remotes', '--list', '*-maintenance'])
    end.split("\n")
  end

  def self.tags_in(repo_path)
    Dir.chdir(repo_path) do
      git('tag')
    end.split("\n")
  end

  def ref_exist?(repo_path, ref)
    Dir.chdir(repo_path) do
      git(['show-ref', '--quiet', ref])
    end

    true
  rescue GitHelper::GitError
    false
  end

  def commit_ids_in(repo_path, revision_id)
    Dir.chdir(repo_path) do
      git(['log', '--format=%H', revision_id, '--'])
    end.split("\n")
  end

  {
    'rspec' => {
      'origin/main'             => { exist: true, orphan: false },
      'origin/2-2-maintenance'  => { exist: true, orphan: false },
      'origin/2-3-maintenance'  => { exist: true, orphan: false },
      'origin/2-5-maintenance'  => { exist: true, orphan: false },
      'origin/2-6-maintenance'  => { exist: true, orphan: false },
      'origin/2-7-maintenance'  => { exist: true, orphan: false },
      'origin/2-9-maintenance'  => { exist: true, orphan: false },
      'origin/2-10-maintenance' => { exist: true, orphan: false },
      'origin/2-11-maintenance' => { exist: true, orphan: false },
      'origin/2-13-maintenance' => { exist: true, orphan: false },
      'origin/2-14-maintenance' => { exist: true, orphan: false },
      'origin/2-99-maintenance' => { exist: true, orphan: false },
      'origin/3-0-maintenance'  => { exist: true, orphan: false },
      'origin/3-1-maintenance'  => { exist: true, orphan: false },
      'origin/3-2-maintenance'  => { exist: true, orphan: false },
      'origin/3-3-maintenance'  => { exist: true, orphan: false },
      'origin/3-4-maintenance'  => { exist: true, orphan: false },
      'origin/3-5-maintenance'  => { exist: true, orphan: false },
      'origin/3-6-maintenance'  => { exist: true, orphan: false },
      'origin/3-7-maintenance'  => { exist: true, orphan: false },
      'origin/3-8-maintenance'  => { exist: true, orphan: false },
      'origin/3-9-maintenance'  => { exist: true, orphan: false },
      'origin/3-10-maintenance' => { exist: true, orphan: false },
      'v2.0.0.a1'               => { exist: true, orphan: false },
      '2.0.0.a2'                => { exist: true, orphan: false },
      '2.0.0.a3'                => { exist: true, orphan: false },
      'v2.0.0.a4'               => { exist: true, orphan: false },
      'v2.0.0.a5'               => { exist: true, orphan: false },
      'v2.0.0.a6'               => { exist: true, orphan: false },
      'v2.0.0.a7'               => { exist: true, orphan: false },
      'v2.0.0.a8'               => { exist: true, orphan: false },
      'v2.0.0.a9'               => { exist: true, orphan: false },
      'v2.0.0.a10'              => { exist: true, orphan: false },
      'v2.0.0.beta.1'           => { exist: true, orphan: false },
      'v2.0.0.beta.2'           => { exist: true, orphan: false },
      'v2.0.0.beta.3'           => { exist: true, orphan: false },
      'v2.0.0.beta.4'           => { exist: true, orphan: false },
      'v2.0.0.beta.5'           => { exist: true, orphan: false },
      'v2.0.0.beta.6'           => { exist: true, orphan: false },
      'v2.0.0.beta.7'           => { exist: true, orphan: false },
      'v2.0.0.beta.8'           => { exist: true, orphan: false },
      'v2.0.0.beta.9'           => { exist: true, orphan: false },
      'v2.0.0.beta.10'          => { exist: true, orphan: false },
      'v2.0.0.beta.11'          => { exist: true, orphan: false },
      'v2.0.0.beta.12'          => { exist: true, orphan: false },
      'v2.0.0.beta.13'          => { exist: true, orphan: false },
      'v2.0.0.beta.14'          => { exist: true, orphan: false },
      'v2.0.0.beta.15'          => { exist: true, orphan: false },
      'v2.0.0.beta.16'          => { exist: true, orphan: false },
      'v2.0.0.beta.17'          => { exist: true, orphan: false },
      'v2.0.0.beta.18'          => { exist: true, orphan: false },
      'v2.0.0.beta.19'          => { exist: true, orphan: false },
      'v2.0.0.beta.20'          => { exist: true, orphan: false },
      'v2.0.0.beta.21'          => { exist: true, orphan: false },
      'v2.0.0.beta.22'          => { exist: true, orphan: false },
      'v2.0.0.rc'               => { exist: true, orphan: false },
      'v2.0.0'                  => { exist: true, orphan: false },
      'v2.0.1'                  => { exist: true, orphan: false },
      'v2.1.0'                  => { exist: true, orphan: false },
      'v2.2.0'                  => { exist: true, orphan: false },
      'v2.3.0'                  => { exist: true, orphan: false },
      'v2.4.0'                  => { exist: true, orphan: false },
      'v2.5.0'                  => { exist: true, orphan: false },
      'v2.6.0.rc1'              => { exist: true, orphan: false },
      'v2.6.0.rc2'              => { exist: true, orphan: false },
      'v2.6.0.rc3'              => { exist: true, orphan: false },
      'v2.6.0.rc4'              => { exist: true, orphan: false },
      'v2.6.0.rc5'              => { exist: true, orphan: false },
      'v2.6.0.rc6'              => { exist: true, orphan: false },
      'v2.6.0'                  => { exist: true, orphan: false },
      'v2.7.0.rc1'              => { exist: true, orphan: false },
      'v2.7.0'                  => { exist: true, orphan: false },
      'v2.8.0.rc1'              => { exist: true, orphan: false },
      'v2.8.0.rc2'              => { exist: true, orphan: false },
      'v2.8.0'                  => { exist: true, orphan: false },
      'v2.9.0.rc1'              => { exist: true, orphan: false },
      'v2.9.0.rc2'              => { exist: true, orphan: false },
      'v2.9.0'                  => { exist: true, orphan: false },
      'v2.10.0'                 => { exist: true, orphan: false },
      'v2.11.0'                 => { exist: true, orphan: false },
      'v2.12.0'                 => { exist: true, orphan: false },
      'v2.13.0'                 => { exist: true, orphan: false },
      'v2.14.0.rc1'             => { exist: true, orphan: false },
      'v2.14.0'                 => { exist: true, orphan: false },
      'v2.14.1'                 => { exist: true, orphan: false },
      'v2.99.0.beta1'           => { exist: true, orphan: false },
      'v2.99.0.beta2'           => { exist: true, orphan: false },
      'v2.99.0.rc1'             => { exist: true, orphan: false },
      'v2.99.0'                 => { exist: true, orphan: false },
      'v3.0.0.beta1'            => { exist: true, orphan: false },
      'v3.0.0.beta2'            => { exist: true, orphan: false },
      'v3.0.0.rc1'              => { exist: true, orphan: false },
      'v3.0.0'                  => { exist: true, orphan: false },
      'v3.1.0'                  => { exist: true, orphan: false },
      'v3.2.0'                  => { exist: true, orphan: false },
      'v3.3.0'                  => { exist: true, orphan: false },
      'v3.4.0'                  => { exist: true, orphan: false },
      'v3.5.0.beta1'            => { exist: true, orphan: false },
      'v3.5.0.beta2'            => { exist: true, orphan: false },
      'v3.5.0.beta3'            => { exist: true, orphan: false },
      'v3.5.0.beta4'            => { exist: true, orphan: false },
      'v3.5.0'                  => { exist: true, orphan: false },
      'v3.6.0.beta1'            => { exist: true, orphan: false },
      'v3.6.0.beta2'            => { exist: true, orphan: false },
      'v3.6.0'                  => { exist: true, orphan: false },
      'v3.7.0'                  => { exist: true, orphan: false },
      'v3.8.0'                  => { exist: true, orphan: false },
      'v3.9.0'                  => { exist: true, orphan: false },
      'v3.10.0'                 => { exist: true, orphan: false },
    },
    'rspec-core' => {
      'origin/main'             => { exist: true, orphan: false },
      'origin/2-2-maintenance'  => { exist: true, orphan: false },
      'origin/2-3-maintenance'  => { exist: true, orphan: false },
      'origin/2-5-maintenance'  => { exist: true, orphan: false },
      'origin/2-6-maintenance'  => { exist: true, orphan: false },
      'origin/2-7-maintenance'  => { exist: true, orphan: false },
      'origin/2-9-maintenance'  => { exist: true, orphan: false },
      'origin/2-10-maintenance' => { exist: true, orphan: false },
      'origin/2-11-maintenance' => { exist: true, orphan: false },
      'origin/2-13-maintenance' => { exist: true, orphan: false },
      'origin/2-14-maintenance' => { exist: true, orphan: false },
      'origin/2-99-maintenance' => { exist: true, orphan: false },
      'origin/3-0-maintenance'  => { exist: true, orphan: false },
      'origin/3-1-maintenance'  => { exist: true, orphan: false },
      'origin/3-2-maintenance'  => { exist: true, orphan: false },
      'origin/3-3-maintenance'  => { exist: true, orphan: false },
      'origin/3-4-maintenance'  => { exist: true, orphan: false },
      'origin/3-5-maintenance'  => { exist: true, orphan: false },
      'origin/3-6-maintenance'  => { exist: true, orphan: false },
      'origin/3-7-maintenance'  => { exist: true, orphan: false },
      'origin/3-8-maintenance'  => { exist: true, orphan: false },
      'origin/3-9-maintenance'  => { exist: true, orphan: false },
      'origin/3-10-maintenance' => { exist: true, orphan: false },
      'v0.0.0'                  => { exist: true, orphan: false },
      'v2.0.0.a1'               => { exist: true, orphan: false },
      '2.0.0.a2'                => { exist: true, orphan: false },
      '2.0.0.a3'                => { exist: true, orphan: false },
      'v2.0.0.a4'               => { exist: true, orphan: false },
      'v2.0.0.a5'               => { exist: true, orphan: false },
      'v2.0.0.a6'               => { exist: true, orphan: false },
      'v2.0.0.a7'               => { exist: true, orphan: false },
      'v2.0.0.a8'               => { exist: true, orphan: false },
      'v2.0.0.a9'               => { exist: true, orphan: false },
      'v2.0.0.a10'              => { exist: true, orphan: false },
      'v2.0.0.beta.1'           => { exist: true, orphan: false },
      'v2.0.0.beta.2'           => { exist: true, orphan: false },
      'v2.0.0.beta.3'           => { exist: true, orphan: false },
      'v2.0.0.beta.4'           => { exist: true, orphan: false },
      'v2.0.0.beta.5'           => { exist: true, orphan: false },
      'v2.0.0.beta.6'           => { exist: true, orphan: false },
      'v2.0.0.beta.7'           => { exist: true, orphan: false },
      'v2.0.0.beta.8'           => { exist: true, orphan: false },
      'v2.0.0.beta.9'           => { exist: true, orphan: false },
      'v2.0.0.beta.10'          => { exist: true, orphan: false },
      'v2.0.0.beta.11'          => { exist: true, orphan: false },
      'v2.0.0.beta.12'          => { exist: true, orphan: false },
      'v2.0.0.beta.13'          => { exist: true, orphan: false },
      'v2.0.0.beta.14'          => { exist: true, orphan: false },
      'v2.0.0.beta.15'          => { exist: true, orphan: false },
      'v2.0.0.beta.16'          => { exist: true, orphan: false },
      'v2.0.0.beta.17'          => { exist: true, orphan: false },
      'v2.0.0.beta.18'          => { exist: true, orphan: false },
      'v2.0.0.beta.19'          => { exist: true, orphan: false },
      'v2.0.0.beta.20'          => { exist: true, orphan: false },
      'v2.0.0.beta.21'          => { exist: true, orphan: false },
      'v2.0.0.beta.22'          => { exist: true, orphan: false },
      'v2.0.0.rc'               => { exist: true, orphan: false },
      'v2.0.0'                  => { exist: true, orphan: false },
      'v2.0.1'                  => { exist: true, orphan: false },
      'v2.1.0'                  => { exist: true, orphan: false },
      'v2.2.0'                  => { exist: true, orphan: false },
      'v2.2.1'                  => { exist: true, orphan: false },
      'v2.3.0'                  => { exist: true, orphan: false },
      'v2.3.1'                  => { exist: true, orphan: false },
      'v2.4.0'                  => { exist: true, orphan: false },
      'v2.5.0'                  => { exist: true, orphan: false },
      'v2.5.1'                  => { exist: true, orphan: false },
      'v2.5.2'                  => { exist: true, orphan: false },
      'v2.6.0.rc1'              => { exist: true, orphan: false },
      'v2.6.0.rc2'              => { exist: true, orphan: false },
      'v2.6.0.rc3'              => { exist: true, orphan: false },
      'v2.6.0.rc4'              => { exist: true, orphan: false },
      'v2.6.0.rc5'              => { exist: true, orphan: false },
      'v2.6.0.rc6'              => { exist: true, orphan: false },
      'v2.6.0'                  => { exist: true, orphan: false },
      'v2.6.1'                  => { exist: true, orphan: false },
      'v2.6.2.rc'               => { exist: true, orphan: false },
      'v2.6.2'                  => { exist: true, orphan: false },
      'v2.6.3.beta1'            => { exist: true, orphan: false },
      'v2.6.3'                  => { exist: true, orphan: false },
      'v2.6.4'                  => { exist: true, orphan: false },
      'v2.7.0.rc1'              => { exist: true, orphan: false },
      'v2.7.0'                  => { exist: true, orphan: false },
      'v2.7.1'                  => { exist: true, orphan: false },
      'v2.8.0.rc1'              => { exist: true, orphan: false },
      'v2.8.0.rc2'              => { exist: true, orphan: false },
      'v2.8.0'                  => { exist: true, orphan: false },
      'v2.9.0.rc1'              => { exist: true, orphan: false },
      'v2.9.0.rc2'              => { exist: true, orphan: false },
      'v2.9.0'                  => { exist: true, orphan: false },
      'v2.10.0'                 => { exist: true, orphan: false },
      'v2.10.1'                 => { exist: true, orphan: false },
      'v2.11.0'                 => { exist: true, orphan: false },
      'v2.11.1'                 => { exist: true, orphan: false },
      'v2.11.2'                 => { exist: true, orphan: true  },
      'v2.11.3'                 => { exist: true, orphan: true  },
      'v2.12.0'                 => { exist: true, orphan: false },
      'v2.12.1'                 => { exist: true, orphan: false },
      'v2.12.2'                 => { exist: true, orphan: false },
      'v2.13.0'                 => { exist: true, orphan: false },
      'v2.13.1'                 => { exist: true, orphan: false },
      'v2.14.0.rc1'             => { exist: true, orphan: false },
      'v2.14.0'                 => { exist: true, orphan: false },
      'v2.14.1'                 => { exist: true, orphan: false },
      'v2.14.2'                 => { exist: true, orphan: false },
      'v2.14.3'                 => { exist: true, orphan: false },
      'v2.14.4'                 => { exist: true, orphan: false },
      'v2.14.5'                 => { exist: true, orphan: false },
      'v2.14.6'                 => { exist: true, orphan: false },
      'v2.14.7'                 => { exist: true, orphan: false },
      'v2.14.8'                 => { exist: true, orphan: false },
      'v2.99.0.beta1'           => { exist: true, orphan: false },
      'v2.99.0.beta2'           => { exist: true, orphan: false },
      'v2.99.0.rc1'             => { exist: true, orphan: false },
      'v2.99.0'                 => { exist: true, orphan: false },
      'v2.99.1'                 => { exist: true, orphan: false },
      'v2.99.2'                 => { exist: true, orphan: false },
      'v3.0.0.beta1'            => { exist: true, orphan: false },
      'v3.0.0.beta2'            => { exist: true, orphan: false },
      'v3.0.0.rc1'              => { exist: true, orphan: false },
      'v3.0.0'                  => { exist: true, orphan: false },
      'v3.0.1'                  => { exist: true, orphan: false },
      'v3.0.2'                  => { exist: true, orphan: false },
      'v3.0.3'                  => { exist: true, orphan: false },
      'v3.0.4'                  => { exist: true, orphan: false },
      'v3.1.0'                  => { exist: true, orphan: false },
      'v3.1.1'                  => { exist: true, orphan: false },
      'v3.1.2'                  => { exist: true, orphan: false },
      'v3.1.3'                  => { exist: true, orphan: false },
      'v3.1.4'                  => { exist: true, orphan: false },
      'v3.1.5'                  => { exist: true, orphan: false },
      'v3.1.6'                  => { exist: true, orphan: false },
      'v3.1.7'                  => { exist: true, orphan: false },
      'v3.2.0'                  => { exist: true, orphan: false },
      'v3.2.1'                  => { exist: true, orphan: false },
      'v3.2.2'                  => { exist: true, orphan: false },
      'v3.2.3'                  => { exist: true, orphan: false },
      'v3.3.0'                  => { exist: true, orphan: false },
      'v3.3.1'                  => { exist: true, orphan: false },
      'v3.3.2'                  => { exist: true, orphan: false },
      'v3.4.0'                  => { exist: true, orphan: false },
      'v3.4.1'                  => { exist: true, orphan: false },
      'v3.4.2'                  => { exist: true, orphan: false },
      'v3.4.3'                  => { exist: true, orphan: false },
      'v3.4.4'                  => { exist: true, orphan: false },
      'v3.5.0.beta1'            => { exist: true, orphan: false },
      'v3.5.0.beta2'            => { exist: true, orphan: false },
      'v3.5.0.beta3'            => { exist: true, orphan: false },
      'v3.5.0.beta4'            => { exist: true, orphan: false },
      'v3.5.0'                  => { exist: true, orphan: false },
      'v3.5.1'                  => { exist: true, orphan: false },
      'v3.5.2'                  => { exist: true, orphan: false },
      'v3.5.3'                  => { exist: true, orphan: false },
      'v3.5.4'                  => { exist: true, orphan: false },
      'v3.6.0.beta1'            => { exist: true, orphan: false },
      'v3.6.0.beta2'            => { exist: true, orphan: false },
      'v3.6.0'                  => { exist: true, orphan: false },
      'v3.7.0'                  => { exist: true, orphan: false },
      'v3.7.1'                  => { exist: true, orphan: false },
      'v3.8.0'                  => { exist: true, orphan: false },
      'v3.8.1'                  => { exist: true, orphan: false },
      'v3.8.2'                  => { exist: true, orphan: false },
      'v3.9.0'                  => { exist: true, orphan: false },
      'v3.9.1'                  => { exist: true, orphan: false },
      'v3.9.2'                  => { exist: true, orphan: false },
      'v3.9.3'                  => { exist: true, orphan: false },
      'v3.10.0'                 => { exist: true, orphan: false },
      'v3.10.1'                 => { exist: true, orphan: false },
    },
    'rspec-expectations' => {
      'origin/main'             => { exist: true, orphan: false },
      'origin/2-2-maintenance'  => { exist: true, orphan: false },
      'origin/2-3-maintenance'  => { exist: true, orphan: false },
      'origin/2-5-maintenance'  => { exist: true, orphan: false },
      'origin/2-6-maintenance'  => { exist: true, orphan: false },
      'origin/2-7-maintenance'  => { exist: true, orphan: false },
      'origin/2-9-maintenance'  => { exist: true, orphan: false },
      'origin/2-10-maintenance' => { exist: true, orphan: false },
      'origin/2-11-maintenance' => { exist: true, orphan: false },
      'origin/2-13-maintenance' => { exist: true, orphan: false },
      'origin/2-14-maintenance' => { exist: true, orphan: false },
      'origin/2-99-maintenance' => { exist: true, orphan: false },
      'origin/3-0-maintenance'  => { exist: true, orphan: false },
      'origin/3-1-maintenance'  => { exist: true, orphan: false },
      'origin/3-2-maintenance'  => { exist: true, orphan: false },
      'origin/3-3-maintenance'  => { exist: true, orphan: false },
      'origin/3-4-maintenance'  => { exist: true, orphan: false },
      'origin/3-5-maintenance'  => { exist: true, orphan: false },
      'origin/3-6-maintenance'  => { exist: true, orphan: false },
      'origin/3-7-maintenance'  => { exist: true, orphan: false },
      'origin/3-8-maintenance'  => { exist: true, orphan: false },
      'origin/3-9-maintenance'  => { exist: true, orphan: false },
      'origin/3-10-maintenance' => { exist: true, orphan: false },
      'v0.0.0'                  => { exist: true, orphan: false },
      'v2.0.0.a1'               => { exist: true, orphan: false },
      '2.0.0.a2'                => { exist: true, orphan: false },
      '2.0.0.a3'                => { exist: true, orphan: false },
      'v2.0.0.a4'               => { exist: true, orphan: false },
      'v2.0.0.a5'               => { exist: true, orphan: false },
      'v2.0.0.a6'               => { exist: true, orphan: false },
      'v2.0.0.a7'               => { exist: true, orphan: false },
      'v2.0.0.a8'               => { exist: true, orphan: false },
      'v2.0.0.a9'               => { exist: true, orphan: false },
      'v2.0.0.a10'              => { exist: true, orphan: false },
      'v2.0.0.beta.1'           => { exist: true, orphan: false },
      'v2.0.0.beta.2'           => { exist: true, orphan: false },
      'v2.0.0.beta.3'           => { exist: true, orphan: false },
      'v2.0.0.beta.4'           => { exist: true, orphan: false },
      'v2.0.0.beta.5'           => { exist: true, orphan: false },
      'v2.0.0.beta.6'           => { exist: true, orphan: false },
      'v2.0.0.beta.7'           => { exist: true, orphan: false },
      'v2.0.0.beta.8'           => { exist: true, orphan: false },
      'v2.0.0.beta.9'           => { exist: true, orphan: false },
      'v2.0.0.beta.10'          => { exist: true, orphan: false },
      'v2.0.0.beta.11'          => { exist: true, orphan: false },
      'v2.0.0.beta.12'          => { exist: true, orphan: false },
      'v2.0.0.beta.13'          => { exist: true, orphan: false },
      'v2.0.0.beta.14'          => { exist: true, orphan: false },
      'v2.0.0.beta.15'          => { exist: true, orphan: false },
      'v2.0.0.beta.16'          => { exist: true, orphan: false },
      'v2.0.0.beta.17'          => { exist: true, orphan: false },
      'v2.0.0.beta.18'          => { exist: true, orphan: false },
      'v2.0.0.beta.19'          => { exist: true, orphan: false },
      'v2.0.0.beta.20'          => { exist: true, orphan: false },
      'v2.0.0.beta.21'          => { exist: true, orphan: false },
      'v2.0.0.beta.22'          => { exist: true, orphan: false },
      'v2.0.0.rc'               => { exist: true, orphan: false },
      'v2.0.0'                  => { exist: true, orphan: false },
      'v2.0.1'                  => { exist: true, orphan: false },
      'v2.1.0'                  => { exist: true, orphan: false },
      'v2.2.0'                  => { exist: true, orphan: false },
      'v2.3.0'                  => { exist: true, orphan: false },
      'v2.4.0'                  => { exist: true, orphan: false },
      'v2.5.0'                  => { exist: true, orphan: false },
      'v2.6.0.rc1'              => { exist: true, orphan: false },
      'v2.6.0.rc2'              => { exist: true, orphan: false },
      'v2.6.0.rc3'              => { exist: true, orphan: false },
      'v2.6.0.rc4'              => { exist: true, orphan: false },
      'v2.6.0.rc5'              => { exist: true, orphan: false },
      'v2.6.0.rc6'              => { exist: true, orphan: false },
      'v2.6.0'                  => { exist: true, orphan: false },
      'v2.7.0.rc1'              => { exist: true, orphan: false },
      'v2.7.0'                  => { exist: true, orphan: false },
      'v2.8.0.rc1'              => { exist: true, orphan: false },
      'v2.8.0.rc2'              => { exist: true, orphan: false },
      'v2.8.0'                  => { exist: true, orphan: false },
      'v2.9.0.rc1'              => { exist: true, orphan: false },
      'v2.9.0.rc2'              => { exist: true, orphan: false },
      'v2.9.0'                  => { exist: true, orphan: false },
      'v2.9.1'                  => { exist: true, orphan: false },
      'v2.10.0'                 => { exist: true, orphan: false },
      'v2.11.0'                 => { exist: true, orphan: false },
      'v2.11.1'                 => { exist: true, orphan: false },
      'v2.11.2'                 => { exist: true, orphan: false },
      'v2.11.3'                 => { exist: true, orphan: false },
      'v2.12.0'                 => { exist: true, orphan: false },
      'v2.12.1'                 => { exist: true, orphan: false },
      'v2.13.0'                 => { exist: true, orphan: false },
      'v2.14.0.rc1'             => { exist: true, orphan: false },
      'v2.14.0'                 => { exist: true, orphan: false },
      'v2.14.1'                 => { exist: true, orphan: false },
      'v2.14.2'                 => { exist: true, orphan: false },
      'v2.14.3'                 => { exist: true, orphan: false },
      'v2.14.4'                 => { exist: true, orphan: false },
      'v2.14.5'                 => { exist: true, orphan: false },
      'v2.99.0.beta1'           => { exist: true, orphan: false },
      'v2.99.0.beta2'           => { exist: true, orphan: false },
      'v2.99.0.rc1'             => { exist: true, orphan: false },
      'v2.99.0'                 => { exist: true, orphan: false },
      'v2.99.1'                 => { exist: true, orphan: false },
      'v2.99.2'                 => { exist: true, orphan: false },
      'v3.0.0.beta1'            => { exist: true, orphan: false },
      'v3.0.0.beta2'            => { exist: true, orphan: false },
      'v3.0.0.rc1'              => { exist: true, orphan: false },
      'v3.0.0'                  => { exist: true, orphan: false },
      'v3.0.1'                  => { exist: true, orphan: false },
      'v3.0.2'                  => { exist: true, orphan: false },
      'v3.0.3'                  => { exist: true, orphan: false },
      'v3.0.4'                  => { exist: true, orphan: false },
      'v3.1.0'                  => { exist: true, orphan: false },
      'v3.1.1'                  => { exist: true, orphan: false },
      'v3.1.2'                  => { exist: true, orphan: false },
      'v3.2.0'                  => { exist: true, orphan: false },
      'v3.2.1'                  => { exist: true, orphan: false },
      'v3.3.0'                  => { exist: true, orphan: false },
      'v3.3.1'                  => { exist: true, orphan: false },
      'v3.4.0'                  => { exist: true, orphan: false },
      'v3.5.0.beta1'            => { exist: true, orphan: false },
      'v3.5.0.beta2'            => { exist: true, orphan: false },
      'v3.5.0.beta3'            => { exist: true, orphan: false },
      'v3.5.0.beta4'            => { exist: true, orphan: false },
      'v3.5.0'                  => { exist: true, orphan: false },
      'v3.6.0.beta1'            => { exist: true, orphan: false },
      'v3.6.0.beta2'            => { exist: true, orphan: false },
      'v3.6.0'                  => { exist: true, orphan: false },
      'v3.7.0'                  => { exist: true, orphan: false },
      'v3.8.0'                  => { exist: true, orphan: false },
      'v3.8.1'                  => { exist: true, orphan: false },
      'v3.8.2'                  => { exist: true, orphan: false },
      'v3.8.3'                  => { exist: true, orphan: false },
      'v3.8.4'                  => { exist: true, orphan: false },
      'v3.8.5'                  => { exist: true, orphan: false },
      'v3.8.6'                  => { exist: true, orphan: false },
      'v3.9.0'                  => { exist: true, orphan: false },
      'v3.9.1'                  => { exist: true, orphan: false },
      'v3.9.2'                  => { exist: true, orphan: false },
      'v3.9.3'                  => { exist: true, orphan: false },
      'v3.9.4'                  => { exist: true, orphan: false },
      'v3.10.0'                 => { exist: true, orphan: false },
      'v3.10.1'                 => { exist: true, orphan: false },
    },
    'rspec-mocks' => {
      'origin/main'             => { exist: true, orphan: false },
      'origin/2-2-maintenance'  => { exist: true, orphan: false },
      'origin/2-3-maintenance'  => { exist: true, orphan: false },
      'origin/2-5-maintenance'  => { exist: true, orphan: false },
      'origin/2-6-maintenance'  => { exist: true, orphan: false },
      'origin/2-7-maintenance'  => { exist: true, orphan: false },
      'origin/2-9-maintenance'  => { exist: true, orphan: false },
      'origin/2-10-maintenance' => { exist: true, orphan: false },
      'origin/2-11-maintenance' => { exist: true, orphan: false },
      'origin/2-13-maintenance' => { exist: true, orphan: false },
      'origin/2-14-maintenance' => { exist: true, orphan: false },
      'origin/2-99-maintenance' => { exist: true, orphan: false },
      'origin/3-0-maintenance'  => { exist: true, orphan: false },
      'origin/3-1-maintenance'  => { exist: true, orphan: false },
      'origin/3-2-maintenance'  => { exist: true, orphan: false },
      'origin/3-3-maintenance'  => { exist: true, orphan: false },
      'origin/3-4-maintenance'  => { exist: true, orphan: false },
      'origin/3-5-maintenance'  => { exist: true, orphan: false },
      'origin/3-6-maintenance'  => { exist: true, orphan: false },
      'origin/3-7-maintenance'  => { exist: true, orphan: false },
      'origin/3-8-maintenance'  => { exist: true, orphan: false },
      'origin/3-9-maintenance'  => { exist: true, orphan: false },
      'origin/3-10-maintenance' => { exist: true, orphan: false },
      'v0.0.0'                  => { exist: true, orphan: false },
      'v2.0.0.a1'               => { exist: true, orphan: false },
      '2.0.0.a2'                => { exist: true, orphan: false },
      '2.0.0.a3'                => { exist: true, orphan: false },
      'v2.0.0.a4'               => { exist: true, orphan: false },
      'v2.0.0.a5'               => { exist: true, orphan: false },
      'v2.0.0.a6'               => { exist: true, orphan: false },
      'v2.0.0.a7'               => { exist: true, orphan: false },
      'v2.0.0.a8'               => { exist: true, orphan: false },
      'v2.0.0.a9'               => { exist: true, orphan: false },
      'v2.0.0.a10'              => { exist: true, orphan: false },
      'v2.0.0.beta.1'           => { exist: true, orphan: false },
      'v2.0.0.beta.2'           => { exist: true, orphan: false },
      'v2.0.0.beta.3'           => { exist: true, orphan: false },
      'v2.0.0.beta.4'           => { exist: true, orphan: false },
      'v2.0.0.beta.5'           => { exist: true, orphan: false },
      'v2.0.0.beta.6'           => { exist: true, orphan: false },
      'v2.0.0.beta.7'           => { exist: true, orphan: false },
      'v2.0.0.beta.8'           => { exist: true, orphan: false },
      'v2.0.0.beta.9'           => { exist: true, orphan: false },
      'v2.0.0.beta.10'          => { exist: true, orphan: false },
      'v2.0.0.beta.11'          => { exist: true, orphan: false },
      'v2.0.0.beta.12'          => { exist: true, orphan: false },
      'v2.0.0.beta.13'          => { exist: true, orphan: false },
      'v2.0.0.beta.14'          => { exist: true, orphan: false },
      'v2.0.0.beta.15'          => { exist: true, orphan: false },
      'v2.0.0.beta.16'          => { exist: true, orphan: false },
      'v2.0.0.beta.17'          => { exist: true, orphan: false },
      'v2.0.0.beta.18'          => { exist: true, orphan: false },
      'v2.0.0.beta.19'          => { exist: true, orphan: false },
      'v2.0.0.beta.20'          => { exist: true, orphan: false },
      'v2.0.0.beta.21'          => { exist: true, orphan: false },
      'v2.0.0.beta.22'          => { exist: true, orphan: false },
      'v2.0.0.rc'               => { exist: true, orphan: false },
      'v2.0.0'                  => { exist: true, orphan: false },
      'v2.0.1'                  => { exist: true, orphan: false },
      'v2.1.0'                  => { exist: true, orphan: false },
      'v2.2.0'                  => { exist: true, orphan: false },
      'v2.2.1'                  => { exist: true, orphan: true  },
      'v2.3.0'                  => { exist: true, orphan: false },
      'v2.3.1'                  => { exist: true, orphan: true  },
      'v2.4.0'                  => { exist: true, orphan: false },
      'v2.5.0'                  => { exist: true, orphan: false },
      'v2.5.1'                  => { exist: true, orphan: true  },
      'v2.5.2'                  => { exist: true, orphan: true  },
      'v2.6.0.rc1'              => { exist: true, orphan: false },
      'v2.6.0.rc2'              => { exist: true, orphan: false },
      'v2.6.0.rc3'              => { exist: true, orphan: false },
      'v2.6.0.rc4'              => { exist: true, orphan: false },
      'v2.6.0.rc5'              => { exist: true, orphan: false },
      'v2.6.0.rc6'              => { exist: true, orphan: false },
      'v2.6.0'                  => { exist: true, orphan: false },
      'v2.6.1'                  => { exist: true, orphan: true  },
      'v2.6.2.rc'               => { exist: true, orphan: true  },
      'v2.6.2'                  => { exist: true, orphan: true  },
      'v2.6.3.beta1'            => { exist: true, orphan: true  },
      'v2.6.3'                  => { exist: true, orphan: true  },
      'v2.6.4'                  => { exist: true, orphan: true  },
      'v2.7.0.rc1'              => { exist: true, orphan: false },
      'v2.7.0'                  => { exist: true, orphan: false },
      'v2.7.1'                  => { exist: true, orphan: true  },
      'v2.8.0.rc1'              => { exist: true, orphan: false },
      'v2.8.0.rc2'              => { exist: true, orphan: false },
      'v2.8.0'                  => { exist: true, orphan: false },
      'v2.9.0.rc1'              => { exist: true, orphan: false },
      'v2.9.0.rc2'              => { exist: true, orphan: false },
      'v2.9.0'                  => { exist: true, orphan: false },
      'v2.10.0'                 => { exist: true, orphan: false },
      'v2.10.1'                 => { exist: true, orphan: false },
      'v2.11.0'                 => { exist: true, orphan: false },
      'v2.11.1'                 => { exist: true, orphan: false },
      'v2.11.2'                 => { exist: true, orphan: false },
      'v2.11.3'                 => { exist: true, orphan: false },
      'v2.12.0'                 => { exist: true, orphan: false },
      'v2.12.1'                 => { exist: true, orphan: false },
      'v2.12.2'                 => { exist: true, orphan: false },
      'v2.13.0'                 => { exist: true, orphan: false },
      'v2.13.1'                 => { exist: true, orphan: false },
      'v2.14.0.rc1'             => { exist: true, orphan: false },
      'v2.14.0'                 => { exist: true, orphan: false },
      'v2.14.1'                 => { exist: true, orphan: false },
      'v2.14.2'                 => { exist: true, orphan: false },
      'v2.14.3'                 => { exist: true, orphan: false },
      'v2.14.4'                 => { exist: true, orphan: false },
      'v2.14.5'                 => { exist: true, orphan: false },
      'v2.14.6'                 => { exist: true, orphan: false },
      'v2.99.0.beta1'           => { exist: true, orphan: false },
      'v2.99.0.beta2'           => { exist: true, orphan: false },
      'v2.99.0.rc1'             => { exist: true, orphan: false },
      'v2.99.0'                 => { exist: true, orphan: false },
      'v2.99.1'                 => { exist: true, orphan: false },
      'v2.99.2'                 => { exist: true, orphan: false },
      'v2.99.3'                 => { exist: true, orphan: false },
      'v2.99.4'                 => { exist: true, orphan: false },
      'v3.0.0.beta1'            => { exist: true, orphan: false },
      'v3.0.0.beta2'            => { exist: true, orphan: false },
      'v3.0.0.rc1'              => { exist: true, orphan: false },
      'v3.0.0'                  => { exist: true, orphan: false },
      'v3.0.1'                  => { exist: true, orphan: false },
      'v3.0.2'                  => { exist: true, orphan: false },
      'v3.0.3'                  => { exist: true, orphan: false },
      'v3.0.4'                  => { exist: true, orphan: false },
      'v3.1.0'                  => { exist: true, orphan: false },
      'v3.1.1'                  => { exist: true, orphan: false },
      'v3.1.2'                  => { exist: true, orphan: false },
      'v3.1.3'                  => { exist: true, orphan: false },
      'v3.2.0'                  => { exist: true, orphan: false },
      'v3.2.1'                  => { exist: true, orphan: false },
      'v3.3.0'                  => { exist: true, orphan: false },
      'v3.3.1'                  => { exist: true, orphan: false },
      'v3.3.2'                  => { exist: true, orphan: false },
      'v3.4.0'                  => { exist: true, orphan: false },
      'v3.4.1'                  => { exist: true, orphan: false },
      'v3.5.0.beta1'            => { exist: true, orphan: false },
      'v3.5.0.beta2'            => { exist: true, orphan: false },
      'v3.5.0.beta3'            => { exist: true, orphan: false },
      'v3.5.0.beta4'            => { exist: true, orphan: false },
      'v3.5.0'                  => { exist: true, orphan: false },
      'v3.6.0.beta1'            => { exist: true, orphan: false },
      'v3.6.0.beta2'            => { exist: true, orphan: false },
      'v3.6.0'                  => { exist: true, orphan: false },
      'v3.7.0'                  => { exist: true, orphan: false },
      'v3.8.0'                  => { exist: true, orphan: false },
      'v3.8.1'                  => { exist: true, orphan: false },
      'v3.8.2'                  => { exist: true, orphan: false },
      'v3.9.0'                  => { exist: true, orphan: false },
      'v3.9.1'                  => { exist: true, orphan: false },
      'v3.10.0'                 => { exist: true, orphan: false },
      'v3.10.1'                 => { exist: true, orphan: false },
      'v3.10.2'                 => { exist: true, orphan: false },
    },
    'rspec-support' => {
      'origin/main'             => { exist: true, orphan: false },
      'origin/2-2-maintenance'  => { exist: false               },
      'origin/2-3-maintenance'  => { exist: false               },
      'origin/2-5-maintenance'  => { exist: false               },
      'origin/2-6-maintenance'  => { exist: false               },
      'origin/2-7-maintenance'  => { exist: false               },
      'origin/2-9-maintenance'  => { exist: false               },
      'origin/2-10-maintenance' => { exist: false               },
      'origin/2-11-maintenance' => { exist: false               },
      'origin/2-13-maintenance' => { exist: false               },
      'origin/2-14-maintenance' => { exist: false               },
      'origin/2-99-maintenance' => { exist: false               },
      'origin/3-0-maintenance'  => { exist: true, orphan: false },
      'origin/3-1-maintenance'  => { exist: true, orphan: false },
      'origin/3-2-maintenance'  => { exist: true, orphan: false },
      'origin/3-3-maintenance'  => { exist: true, orphan: false },
      'origin/3-4-maintenance'  => { exist: true, orphan: false },
      'origin/3-5-maintenance'  => { exist: true, orphan: false },
      'origin/3-6-maintenance'  => { exist: true, orphan: false },
      'origin/3-7-maintenance'  => { exist: true, orphan: false },
      'origin/3-8-maintenance'  => { exist: true, orphan: false },
      'origin/3-9-maintenance'  => { exist: true, orphan: false },
      'origin/3-10-maintenance' => { exist: true, orphan: false },
      'v3.0.0.beta1'            => { exist: true, orphan: false },
      'v3.0.0.beta2'            => { exist: true, orphan: false },
      'v3.0.0.rc1'              => { exist: true, orphan: false },
      'v3.0.0'                  => { exist: true, orphan: false },
      'v3.0.1'                  => { exist: true, orphan: false },
      'v3.0.2'                  => { exist: true, orphan: false },
      'v3.0.3'                  => { exist: true, orphan: false },
      'v3.0.4'                  => { exist: true, orphan: false },
      'v3.1.0'                  => { exist: true, orphan: false },
      'v3.1.1'                  => { exist: true, orphan: false },
      'v3.1.2'                  => { exist: true, orphan: false },
      'v3.2.0'                  => { exist: true, orphan: false },
      'v3.2.1'                  => { exist: true, orphan: false },
      'v3.2.2'                  => { exist: true, orphan: false },
      'v3.3.0'                  => { exist: true, orphan: false },
      'v3.4.0'                  => { exist: true, orphan: false },
      'v3.4.1'                  => { exist: true, orphan: false },
      'v3.5.0.beta1'            => { exist: true, orphan: false },
      'v3.5.0.beta2'            => { exist: true, orphan: false },
      'v3.5.0.beta3'            => { exist: true, orphan: false },
      'v3.5.0.beta4'            => { exist: true, orphan: false },
      'v3.5.0'                  => { exist: true, orphan: false },
      'v3.6.0.beta1'            => { exist: true, orphan: false },
      'v3.6.0.beta2'            => { exist: true, orphan: false },
      'v3.6.0'                  => { exist: true, orphan: false },
      'v3.7.0'                  => { exist: true, orphan: false },
      'v3.7.1'                  => { exist: true, orphan: false },
      'v3.8.0'                  => { exist: true, orphan: false },
      'v3.8.2'                  => { exist: true, orphan: false },
      'v3.8.3'                  => { exist: true, orphan: false },
      'v3.9.0'                  => { exist: true, orphan: false },
      'v3.9.1'                  => { exist: true, orphan: false },
      'v3.9.2'                  => { exist: true, orphan: false },
      'v3.9.3'                  => { exist: true, orphan: false },
      'v3.9.4'                  => { exist: true, orphan: false },
      'v3.10.0'                 => { exist: true, orphan: false },
      'v3.10.1'                 => { exist: true, orphan: false },
      'v3.10.2'                 => { exist: true, orphan: false },
    }
  }.each do |repo_name, refs|
    describe repo_name do
      repo_path = repo_name

      refs.each do |ref, expected_results|
        describe ref do
          if expected_results[:exist]
            it 'exists' do
              expect(ref_exist?(repo_path, ref)).to be true
            end
          else
            it 'does not exist' do
              expect(ref_exist?(repo_path, ref)).to be false
            end
          end

          let(:target_ref_commit_ids) do
            commit_ids_in(repo_path, ref)
          end

          let(:main_branch_commit_ids) do
            commit_ids_in(repo_path, 'origin/main')
          end

          def skip_if_ref_does_not_exist
            yield
          rescue GitHelper::GitError => error
            if error.message.include?('bad revision')
              skip 'ref does not exist'
            else
              raise error
            end
          end

          if expected_results[:orphan] == true
            it 'is an orphan ref which shares no commits with main branch' do
              expect(target_ref_commit_ids & main_branch_commit_ids).to be_empty
            end
          elsif expected_results[:orphan] == false
            it 'has the same root commit as main branch' do
              expect(target_ref_commit_ids.last).to eq(main_branch_commit_ids.last)
              expect(target_ref_commit_ids & main_branch_commit_ids).not_to be_empty
            end
          end
        end
      end
    end
  end
end
